[project]
name = "my-actf-workspace"
version = "0.1.0"
requires-python = ">=3.11"

[tool.uv.workspace]
members = [
    "0-data-writing",
    "1-raw-data-ingest",
    "2-data-prep",
    "3-model-training",
    "4-model-eval",
]

[tool.ruff]
target-version = "py311"
line-length = 100
exclude = [".git", ".venv", "__pycache__", "build", "dist"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "UP", # pyupgrade
    "B",  # flake8-bugbear
]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
